export const mockPokemons = [
  {
    id: 25,
    name: "pikachu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif",
    types: ["electric"],
    hp: 35,
    attack: 55,
    defense: 40,
    speed: 90,
    height: "0.4 m",
    weight: "6.0 kg",
    abilities: ["static", "lightning-rod"],
  },
  {
    id: 1,
    name: "bulbasaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/1.gif",
    types: ["grass", "poison"],
    hp: 45,
    attack: 49,
    defense: 49,
    speed: 45,
    height: "0.7 m",
    weight: "6.9 kg",
    abilities: ["overgrow", "chlorophyll"],
  },
  {
    id: 4,
    name: "charmander",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/4.gif",
    types: ["fire"],
    hp: 39,
    attack: 52,
    defense: 43,
    speed: 65,
    height: "0.6 m",
    weight: "8.5 kg",
    abilities: ["blaze", "solar-power"],
  },
  {
    id: 7,
    name: "squirtle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/7.gif",
    types: ["water"],
    hp: 44,
    attack: 48,
    defense: 65,
    speed: 43,
    height: "0.5 m",
    weight: "9.0 kg",
    abilities: ["torrent", "rain-dish"],
  },
  {
    id: 94,
    name: "gengar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/94.gif",
    types: ["ghost", "poison"],
    hp: 60,
    attack: 65,
    defense: 60,
    speed: 110,
    height: "1.5 m",
    weight: "40.5 kg",
    abilities: ["cursed-body"],
  },
  {
    id: 130,
    name: "gyarados",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/130.gif",
    types: ["water", "flying"],
    hp: 95,
    attack: 125,
    defense: 79,
    speed: 81,
    height: "6.5 m",
    weight: "235.0 kg",
    abilities: ["intimidate", "moxie"],
  },
  {
    id: 143,
    name: "snorlax",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/143.gif",
    types: ["normal"],
    hp: 160,
    attack: 110,
    defense: 65,
    speed: 30,
    height: "2.1 m",
    weight: "460.0 kg",
    abilities: ["immunity", "thick-fat", "gluttony"],
  },
  {
    id: 39,
    name: "jigglypuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/39.gif",
    types: ["normal", "fairy"],
    hp: 115,
    attack: 45,
    defense: 20,
    speed: 20,
    height: "0.5 m",
    weight: "5.5 kg",
    abilities: ["cute-charm", "competitive", "friend-guard"],
  },
  {
    id: 149,
    name: "dragonite",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/149.gif",
    types: ["dragon", "flying"],
    hp: 91,
    attack: 134,
    defense: 95,
    speed: 80,
    height: "2.2 m",
    weight: "210.0 kg",
    abilities: ["inner-focus", "multiscale"],
  },
  {
    id: 150,
    name: "mewtwo",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/150.gif",
    types: ["psychic"],
    hp: 106,
    attack: 110,
    defense: 90,
    speed: 130,
    height: "2.0 m",
    weight: "122.0 kg",
    abilities: ["pressure", "unnerve"],
  },
  {
    id: 282,
    name: "gardevoir",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/282.gif",
    types: ["psychic", "fairy"],
    hp: 68,
    attack: 65,
    defense: 65,
    speed: 80,
    height: "1.6 m",
    weight: "48.4 kg",
    abilities: ["synchronize", "trace", "telepathy"],
  },
  {
    id: 448,
    name: "lucario",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/448.gif",
    types: ["fighting", "steel"],
    hp: 70,
    attack: 110,
    defense: 70,
    speed: 90,
    height: "1.2 m",
    weight: "54.0 kg",
    abilities: ["steadfast", "inner-focus", "justified"],
  },
  {
    id: 25,
    name: "pikachu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif",
    types: ["electric"],
    hp: 35,
    attack: 55,
    defense: 40,
    speed: 90,
    height: "0.4 m",
    weight: "6.0 kg",
    abilities: ["static", "lightning-rod"],
  },
  {
    id: 1,
    name: "bulbasaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/1.gif",
    types: ["grass", "poison"],
    hp: 45,
    attack: 49,
    defense: 49,
    speed: 45,
    height: "0.7 m",
    weight: "6.9 kg",
    abilities: ["overgrow", "chlorophyll"],
  },
  {
    id: 4,
    name: "charmander",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/4.gif",
    types: ["fire"],
    hp: 39,
    attack: 52,
    defense: 43,
    speed: 65,
    height: "0.6 m",
    weight: "8.5 kg",
    abilities: ["blaze", "solar-power"],
  },
  {
    id: 7,
    name: "squirtle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/7.gif",
    types: ["water"],
    hp: 44,
    attack: 48,
    defense: 65,
    speed: 43,
    height: "0.5 m",
    weight: "9.0 kg",
    abilities: ["torrent", "rain-dish"],
  },
  {
    id: 94,
    name: "gengar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/94.gif",
    types: ["ghost", "poison"],
    hp: 60,
    attack: 65,
    defense: 60,
    speed: 110,
    height: "1.5 m",
    weight: "40.5 kg",
    abilities: ["cursed-body"],
  },
  {
    id: 130,
    name: "gyarados",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/130.gif",
    types: ["water", "flying"],
    hp: 95,
    attack: 125,
    defense: 79,
    speed: 81,
    height: "6.5 m",
    weight: "235.0 kg",
    abilities: ["intimidate", "moxie"],
  },
  {
    id: 143,
    name: "snorlax",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/143.gif",
    types: ["normal"],
    hp: 160,
    attack: 110,
    defense: 65,
    speed: 30,
    height: "2.1 m",
    weight: "460.0 kg",
    abilities: ["immunity", "thick-fat", "gluttony"],
  },
  {
    id: 39,
    name: "jigglypuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/39.gif",
    types: ["normal", "fairy"],
    hp: 115,
    attack: 45,
    defense: 20,
    speed: 20,
    height: "0.5 m",
    weight: "5.5 kg",
    abilities: ["cute-charm", "competitive", "friend-guard"],
  },
  {
    id: 149,
    name: "dragonite",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/149.gif",
    types: ["dragon", "flying"],
    hp: 91,
    attack: 134,
    defense: 95,
    speed: 80,
    height: "2.2 m",
    weight: "210.0 kg",
    abilities: ["inner-focus", "multiscale"],
  },
  {
    id: 150,
    name: "mewtwo",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/150.gif",
    types: ["psychic"],
    hp: 106,
    attack: 110,
    defense: 90,
    speed: 130,
    height: "2.0 m",
    weight: "122.0 kg",
    abilities: ["pressure", "unnerve"],
  },
  {
    id: 282,
    name: "gardevoir",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/282.gif",
    types: ["psychic", "fairy"],
    hp: 68,
    attack: 65,
    defense: 65,
    speed: 80,
    height: "1.6 m",
    weight: "48.4 kg",
    abilities: ["synchronize", "trace", "telepathy"],
  },
  {
    id: 448,
    name: "lucario",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/448.gif",
    types: ["fighting", "steel"],
    hp: 70,
    attack: 110,
    defense: 70,
    speed: 90,
    height: "1.2 m",
    weight: "54.0 kg",
    abilities: ["steadfast", "inner-focus", "justified"],
  },
  // 38 nuevos Pokémon
  {
    id: 6,
    name: "charizard",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/6.gif",
    types: ["fire", "flying"],
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100,
    height: "1.7 m",
    weight: "90.5 kg",
    abilities: ["blaze", "solar-power"],
  },
  {
    id: 9,
    name: "blastoise",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/9.gif",
    types: ["water"],
    hp: 79,
    attack: 83,
    defense: 100,
    speed: 78,
    height: "1.6 m",
    weight: "85.5 kg",
    abilities: ["torrent", "rain-dish"],
  },
  {
    id: 59,
    name: "arcanine",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/59.gif",
    types: ["fire"],
    hp: 90,
    attack: 110,
    defense: 80,
    speed: 95,
    height: "1.9 m",
    weight: "155.0 kg",
    abilities: ["intimidate", "flash-fire", "justified"],
  },
  {
    id: 65,
    name: "alakazam",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/65.gif",
    types: ["psychic"],
    hp: 55,
    attack: 50,
    defense: 45,
    speed: 120,
    height: "1.5 m",
    weight: "48.0 kg",
    abilities: ["synchronize", "inner-focus", "magic-guard"],
  },
  {
    id: 68,
    name: "machamp",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/68.gif",
    types: ["fighting"],
    hp: 90,
    attack: 130,
    defense: 80,
    speed: 55,
    height: "1.6 m",
    weight: "130.0 kg",
    abilities: ["guts", "no-guard", "steadfast"],
  },
  {
    id: 76,
    name: "golem",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/76.gif",
    types: ["rock", "ground"],
    hp: 80,
    attack: 120,
    defense: 130,
    speed: 45,
    height: "1.4 m",
    weight: "300.0 kg",
    abilities: ["rock-head", "sturdy", "sand-veil"],
  },
  {
    id: 131,
    name: "lapras",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/131.gif",
    types: ["water", "ice"],
    hp: 130,
    attack: 85,
    defense: 80,
    speed: 60,
    height: "2.5 m",
    weight: "220.0 kg",
    abilities: ["water-absorb", "shell-armor", "hydration"],
  },
  {
    id: 133,
    name: "eevee",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/133.gif",
    types: ["normal"],
    hp: 55,
    attack: 55,
    defense: 50,
    speed: 55,
    height: "0.3 m",
    weight: "6.5 kg",
    abilities: ["run-away", "adaptability", "anticipation"],
  },
  {
    id: 134,
    name: "vaporeon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/134.gif",
    types: ["water"],
    hp: 130,
    attack: 65,
    defense: 60,
    speed: 65,
    height: "1.0 m",
    weight: "29.0 kg",
    abilities: ["water-absorb", "hydration"],
  },
  {
    id: 135,
    name: "jolteon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/135.gif",
    types: ["electric"],
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 130,
    height: "0.8 m",
    weight: "24.5 kg",
    abilities: ["volt-absorb", "quick-feet"],
  },
  {
    id: 136,
    name: "flareon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/136.gif",
    types: ["fire"],
    hp: 65,
    attack: 130,
    defense: 60,
    speed: 65,
    height: "0.9 m",
    weight: "25.0 kg",
    abilities: ["flash-fire", "guts"],
  },
  {
    id: 157,
    name: "typhlosion",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/157.gif",
    types: ["fire"],
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100,
    height: "1.7 m",
    weight: "79.5 kg",
    abilities: ["blaze", "flash-fire"],
  },
  {
    id: 160,
    name: "feraligatr",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/160.gif",
    types: ["water"],
    hp: 85,
    attack: 105,
    defense: 100,
    speed: 78,
    height: "2.3 m",
    weight: "88.8 kg",
    abilities: ["torrent", "sheer-force"],
  },
  {
    id: 181,
    name: "ampharos",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/181.gif",
    types: ["electric"],
    hp: 90,
    attack: 75,
    defense: 85,
    speed: 55,
    height: "1.4 m",
    weight: "61.5 kg",
    abilities: ["static", "plus"],
  },
  {
    id: 196,
    name: "espeon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/196.gif",
    types: ["psychic"],
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 110,
    height: "0.9 m",
    weight: "26.5 kg",
    abilities: ["synchronize", "magic-bounce"],
  },
  {
    id: 197,
    name: "umbreon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/197.gif",
    types: ["dark"],
    hp: 95,
    attack: 65,
    defense: 110,
    speed: 65,
    height: "1.0 m",
    weight: "27.0 kg",
    abilities: ["synchronize", "inner-focus"],
  },
  {
    id: 212,
    name: "scizor",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/212.gif",
    types: ["bug", "steel"],
    hp: 70,
    attack: 130,
    defense: 100,
    speed: 65,
    height: "1.8 m",
    weight: "118.0 kg",
    abilities: ["swarm", "technician", "light-metal"],
  },
  {
    id: 214,
    name: "heracross",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/214.gif",
    types: ["bug", "fighting"],
    hp: 80,
    attack: 125,
    defense: 75,
    speed: 85,
    height: "1.5 m",
    weight: "54.0 kg",
    abilities: ["swarm", "guts", "moxie"],
  },
  {
    id: 248,
    name: "tyranitar",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/248.gif",
    types: ["rock", "dark"],
    hp: 100,
    attack: 134,
    defense: 110,
    speed: 61,
    height: "2.0 m",
    weight: "202.0 kg",
    abilities: ["sand-stream", "unnerve"],
  },
  {
    id: 257,
    name: "blaziken",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/257.gif",
    types: ["fire", "fighting"],
    hp: 80,
    attack: 120,
    defense: 70,
    speed: 80,
    height: "1.9 m",
    weight: "52.0 kg",
    abilities: ["blaze", "speed-boost"],
  },
  {
    id: 260,
    name: "swampert",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/260.gif",
    types: ["water", "ground"],
    hp: 100,
    attack: 110,
    defense: 90,
    speed: 60,
    height: "1.5 m",
    weight: "81.9 kg",
    abilities: ["torrent", "damp"],
  },
  {
    id: 306,
    name: "aggron",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/306.gif",
    types: ["steel", "rock"],
    hp: 70,
    attack: 110,
    defense: 180,
    speed: 50,
    height: "2.1 m",
    weight: "360.0 kg",
    abilities: ["sturdy", "rock-head", "heavy-metal"],
  },
  {
    id: 330,
    name: "flygon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/330.gif",
    types: ["ground", "dragon"],
    hp: 80,
    attack: 100,
    defense: 80,
    speed: 100,
    height: "2.0 m",
    weight: "82.0 kg",
    abilities: ["levitate"],
  },
  {
    id: 373,
    name: "salamence",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/373.gif",
    types: ["dragon", "flying"],
    hp: 95,
    attack: 135,
    defense: 80,
    speed: 100,
    height: "1.5 m",
    weight: "102.6 kg",
    abilities: ["intimidate", "moxie"],
  },
  {
    id: 376,
    name: "metagross",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/376.gif",
    types: ["steel", "psychic"],
    hp: 80,
    attack: 135,
    defense: 130,
    speed: 70,
    height: "1.6 m",
    weight: "550.0 kg",
    abilities: ["clear-body", "light-metal"],
  },
  {
    id: 392,
    name: "infernape",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/392.gif",
    types: ["fire", "fighting"],
    hp: 76,
    attack: 104,
    defense: 71,
    speed: 108,
    height: "1.2 m",
    weight: "55.0 kg",
    abilities: ["blaze", "iron-fist"],
  },
  {
    id: 445,
    name: "garchomp",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/445.gif",
    types: ["dragon", "ground"],
    hp: 108,
    attack: 130,
    defense: 95,
    speed: 102,
    height: "1.9 m",
    weight: "95.0 kg",
    abilities: ["sand-veil", "rough-skin"],
  },
  {
    id: 468,
    name: "togekiss",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/468.gif",
    types: ["fairy", "flying"],
    hp: 85,
    attack: 50,
    defense: 95,
    speed: 80,
    height: "1.5 m",
    weight: "38.0 kg",
    abilities: ["hustle", "serene-grace", "super-luck"],
  },
  {
    id: 470,
    name: "leafeon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/470.gif",
    types: ["grass"],
    hp: 65,
    attack: 110,
    defense: 130,
    speed: 95,
    height: "1.0 m",
    weight: "25.5 kg",
    abilities: ["leaf-guard", "chlorophyll"],
  },
  {
    id: 471,
    name: "glaceon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/471.gif",
    types: ["ice"],
    hp: 65,
    attack: 60,
    defense: 110,
    speed: 65,
    height: "0.8 m",
    weight: "25.9 kg",
    abilities: ["snow-cloak", "ice-body"],
  },
  {
    id: 571,
    name: "zoroark",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/571.gif",
    types: ["dark"],
    hp: 60,
    attack: 105,
    defense: 60,
    speed: 105,
    height: "1.6 m",
    weight: "81.1 kg",
    abilities: ["illusion"],
  },
  {
    id: 635,
    name: "hydreigon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/635.gif",
    types: ["dark", "dragon"],
    hp: 92,
    attack: 105,
    defense: 90,
    speed: 98,
    height: "1.8 m",
    weight: "160.0 kg",
    abilities: ["levitate"],
  },
  {
    id: 658,
    name: "greninja",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/658.gif",
    types: ["water", "dark"],
    hp: 72,
    attack: 95,
    defense: 67,
    speed: 122,
    height: "1.5 m",
    weight: "40.0 kg",
    abilities: ["torrent", "protean", "battle-bond"],
  },
  {
    id: 700,
    name: "sylveon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/700.gif",
    types: ["fairy"],
    hp: 95,
    attack: 65,
    defense: 65,
    speed: 60,
    height: "1.0 m",
    weight: "23.5 kg",
    abilities: ["cute-charm", "pixilate"],
  },
];
